import type { Metadata } from 'next'
import './globals.css'
import Navbar from "../components/Navbar"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import AuthProvider from "../components/AuthProvider"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthProvider>
      <body>
        <Navbar/>
        <div className='pl-[100px] bg-darkblue'>
        {children}
        </div>
        </body>
      </AuthProvider>
    </html>
  )
}
